name: Reject pending deployments

inputs:
  token:
    description: Github Access Token
    required: true
  environment:
    description: Environment
    required: true
  branch:
    description: Branch
    default: ${{ github.event.pull_request.head.ref }}
  preserve-latest:
    description: Preserve latest pending deployment
    default: false
  sha:
    description: Git sha1
    default: ${{ github.event.pull_request.head.sha }}

runs:
  using: "composite"
  steps:
    - name: Set JQ filter
      id: set-jq-filter
      shell: bash
      run: |
        JQ_FILTER_NONE='.workflow_runs[] | .id'
        JQ_FILTER_PRESERVE_LATEST='.workflow_runs[] | select(.head_sha != "${{ inputs.sha }}") | .id'
        echo "JQ_FILTER='${{ inputs.preserve-latest == 'true' && '$JQ_FILTER_PRESERVE_LATEST' || '$JQ_FILTER_NONE' }}'"  >> $GITHUB_ENV

    - name: List runs with waiting status related to (${{ inputs.branch }})
      id: list-waiting-runs
      shell: bash
      run: |
        curl -L --output waiting_runs.json \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs?status=waiting&branch=${{ inputs.branch }}

    - name: Get pending deployments
      id: pending-deployments
      shell: bash
      run: |
        cat waiting_runs.json | jq '.workflow_runs[] | .id' | while read run_id;do
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/pending_deployments
        done

    # - name: Display pending deployments
    #   id: pending-deployments
    #   shell: bash
    #   run : cat pending-deploys.json |

    - name: Display filter
      id: display-filter
      shell: bash
      run: cat waiting_runs.json | jq '.workflow_runs[] | .id'

    - name: Display environment
      id: display-env
      shell: bash
      run: echo ${{ inputs.environment }}

    - name: Reject all pending deployments
      id: reject-pending-deployments
      shell: bash
      run: |
        cat waiting_runs.json | jq ${{ env.JQ_FILTER }} | while read run_id;do
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/pending_deployments \
            -d '{"environment_ids":[161171787],"state":"rejected","comment":"Rejected by API"}'
        done
